apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: argocd
commonLabels:
  variant: production
resources:
  - ns.yaml
  - demo-kustomize-guestbook.yaml
  - demo-nextjs.yaml