apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: prod-demo-kustomize-guestbook
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: prod-demo-nextjs